### ISSUE TITLE
Templates error on systemRDL SignalNodes

### ISSUE THREAD

**Issue by apstrike** [krcb197/PeakRDL-python#81]
It seems that PeakRDL-Python can't generate register models for systemRDL models with registers.
for example on the following input RDL file:

```
addrmap addrmap_with_signal {
    default regwidth = 32;
    default accesswidth = 32;

    signal {signalwidth=1; sync; activehigh;
    } my_signal;

    reg {
        default sw = r;
        default hw = w;

        field {} my_field[32];
    } my_reg;

    my_reg.my_field->resetsignal = my_signal;
};
```

I see the following error:

```
Traceback (most recent call last):
  File "/home/STRIKETECH/aporat/.local/bin/peakrdl", line 11, in <module>
    load_entry_point('peakrdl', 'console_scripts', 'peakrdl')()
  File "/home/STRIKETECH/aporat/systemrdl-gts/PeakRDL/src/peakrdl/main.py", line 92, in main
    options.subcommand.main(options)
  File "/home/STRIKETECH/aporat/systemrdl-gts/PeakRDL/src/peakrdl/subcommand.py", line 133, in main
    self.do_export(top, options)
  File "/home/STRIKETECH/aporat/systemrdl-gts/PeakRDL/src/peakrdl/plugins/exporter.py", line 67, in do_export
    func(top_node, options)
  File "/home/STRIKETECH/aporat/PeakRDL-python/src/peakrdl_python/__peakrdl__.py", line 58, in do_export
    skip_test_case_generation=options.skip_test_case_generation
  File "/home/STRIKETECH/aporat/PeakRDL-python/src/peakrdl_python/exporter.py", line 174, in export
    stream.dump(module_fqfn, encoding='utf-8')
  File "/home/STRIKETECH/aporat/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1618, in dump
    fp.writelines(iterable)
  File "/home/STRIKETECH/aporat/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1613, in <genexpr>
    iterable = (x.encode(encoding, errors) for x in self)  # type: ignore
  File "/home/STRIKETECH/aporat/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1662, in __next__
    return self._next()  # type: ignore
  File "/home/STRIKETECH/aporat/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1354, in generate
    yield self.environment.handle_exception()
  File "/home/STRIKETECH/aporat/.local/lib/python3.7/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/STRIKETECH/aporat/PeakRDL-python/src/peakrdl_python/templates/addrmap.py.jinja", line 343, in top-level template code
    {{ addrmap_class(node) }}
  File "/home/STRIKETECH/aporat/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "/home/STRIKETECH/aporat/PeakRDL-python/src/peakrdl_python/templates/addrmap.py.jinja", line 247, in template
    {{ raise_template_error('unexpected type') }}
  File "/home/STRIKETECH/aporat/PeakRDL-python/src/peakrdl_python/exporter.py", line 288, in _raise_template_error
    raise PythonExportTemplateError(message)
peakrdl_python.exporter.PythonExportTemplateError: unexpected type
```
I'm not sure if systemRDL signal nodes are intended to just overall be ignored by the python register model, or if they're intended to be included somewhere.

**Comment by krcb197** [comment]
@apstrike, thank you for you interest in this project. This example should have worked.

The python wrappers were intended to largely ignore signals. I took the view that you can't interact with them programmatically. In fact there are test cases in unit tests that cover exactly the case you have highlighted: a signal resetting a register. Please reach out to me if you disagree.

I have discovered that all my test case defined the signal outside of the address map, so if you redo the example as follows it works:
```systemRDL
signal {signalwidth=1; sync; activehigh;} my_signal;

addrmap addrmap_with_signal {
    default regwidth = 32;
    default accesswidth = 32;

    reg {
        default sw = r;
        default hw = w;

        field {} my_field[32];
    } my_reg;

    my_reg.my_field->resetsignal = my_signal;
};
```

I will add this case to the tests and get a fix out ASAP.

**Comment by krcb197** [comment]
This has been fixed in the new release 0.3.11; Please let me know if you encounter any further issues.

**Comment by apstrike** [comment]
@krcb197 thanks for such a quick fix. It looks like for this case things now work. but in the case that the signal is instantiated in a regfile, the program still errors out due to an unexpected type, specifically at `/src/peakrdl_python/templates/addrmap.py.jinja", line 141, in template`.

if the intent is to ignore signal nodes (and I agree I don't think you can interact with them on the software side) I wonder if it would be better to filter them out when accessing node children or descendants using the filtering jinja templates allow in for loops, for ex: `{% for child_node in node.children() if not isinstance(child_node, systemrdlSignalNode) %}` ?

**Comment by krcb197** [comment]
Re-opening based on the comments, I have studied the specification a bit more and discovered that signals can be defined at multiple places in the structure, including:

- Inside registers
- inside fields
- inside memories

re-opening this ticket to address these other cases

**Comment by krcb197** [comment]
@apstrike I have had a second attempt at addressing all the places a signal can get defined. Hopefully, I have got them all this time.

**Comment by apstrike** [comment]
0.3.12 all looks good to me. Thanks
